stages:
  - build
  - deploy
variables:
  NODE_ENV: development
  DOCKER_IMAGE_NAME: "moly-prototype"
  DOCKER_ORIGIN_PORT: "5003"
  DOCKER_REMOTE_PORT: "5003"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build_client:
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - docker build -t $DOCKER_IMAGE_NAME:latest .
    - docker stop $DOCKER_IMAGE_NAME || true
    - docker rm $DOCKER_IMAGE_NAME || true

deploy:
  stage: deploy
  script:
    - docker run --name $DOCKER_IMAGE_NAME -p $DOCKER_REMOTE_PORT:$DOCKER_ORIGIN_PORT -d $DOCKER_IMAGE_NAME:latest
  only:
    - main
